"use client";
import { useEffect, useState } from "react";
import { Check, ExternalLink, FlaskConical, Plus, Power, PowerOff, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/lib/i18n";
import { createNewsSource, fetchNewsSources, fetchNewsSuggestions, reviewNewsSuggestion, testNewsSource, updateNewsSource, type NewsSourceForm } from "./ai-news-api";
import type { NewsSource, NewsSuggestion } from "./ai-news-types";

const EMPTY_SOURCE: NewsSourceForm = { provider_key: "", provider_name: "", name: "", url: "https://", kind: "release_notes", active: false, reason: "Add verified official model release source" };

/** Manage the first-party source registry and reviewed web-discovery suggestions. */
export function NewsSources() {
  const { t } = useLanguage();
  const [sources, setSources] = useState<NewsSource[]>([]), [suggestions, setSuggestions] = useState<NewsSuggestion[]>([]), [form, setForm] = useState<NewsSourceForm>(EMPTY_SOURCE), [testResult, setTestResult] = useState<Record<string, unknown> | null>(null), [message, setMessage] = useState("");
  /** Reload both source lists after any curator action. */
  async function reload() { try { const [sourceValues, suggestionValues] = await Promise.all([fetchNewsSources(), fetchNewsSuggestions()]); setSources(sourceValues); setSuggestions(suggestionValues); setMessage(""); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Sources unavailable"); } }
  useEffect(/** Load registry state when the source tab opens. */ function initialize() { void reload(); }, []);
  /** Update one form property without duplicating field handlers. */
  function change<Key extends keyof NewsSourceForm>(key: Key, value: NewsSourceForm[Key]) { setForm({ ...form, [key]: value }); }
  /** Live-test the current safe source without retaining it. */
  async function test() { try { setTestResult(await testNewsSource(form)); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Validation failed"); } }
  /** Create the current form source and reset the add panel. */
  async function create() { try { await createNewsSource(form); setForm(EMPTY_SOURCE); setTestResult(null); await reload(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Source creation failed"); } }
  /** Enable or disable one source through mandatory revalidation and auditing. */
  async function toggle(source: NewsSource) { try { await updateNewsSource(source.id, { provider_key: source.provider_key, provider_name: source.provider_name, name: source.name, url: source.url, kind: source.kind, active: !source.active, reason: source.active ? "Disable official source" : "Reactivate verified official source" }); await reload(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Source update failed"); } }
  /** Dismiss an untrusted discovered source after curator review. */
  async function dismiss(suggestion: NewsSuggestion) { await reviewNewsSuggestion(suggestion.id, { action: "dismiss", reason: "Not approved for the official registry" }); await reload(); }
  return <div className="news-source-layout">
    <section className="news-panel"><header><div><span className="eyebrow">{t("TRUSTED INPUT", "ENTRADA DE CONFIANZA")}</span><h2>{t("Official registry", "Registro oficial")}</h2></div><span>{sources.filter(/** Count enabled official endpoints only. */ function active(source) { return source.active; }).length} {t("active", "activas")}</span></header>{message ? <div className="notice error" role="alert">{message}</div> : null}<div className="news-source-list">{sources.map(/** Render one verified or disabled registry endpoint. */ function renderSource(source) { return <article key={source.id}><div className="news-source-provider"><span className={`news-source-state ${source.active ? "active" : ""}`} /><div><strong>{source.provider_name}</strong><span>{source.name}</span></div></div><a href={source.url} target="_blank" rel="noopener noreferrer">{new URL(source.url).hostname}<ExternalLink aria-hidden="true" size={14} /></a><span className={`news-validation ${source.validation_status}`}>{source.validation_status}</span><Button variant="ghost" size="icon" aria-label={source.active ? t("Disable source", "Desactivar fuente") : t("Enable source", "Activar fuente")} onClick={/** Toggle this registry endpoint through the protected API. */ function switchSource() { void toggle(source); }}>{source.active ? <Power aria-hidden="true" /> : <PowerOff aria-hidden="true" />}</Button></article>; })}</div></section>
    <section className="news-panel news-source-form"><header><div><span className="eyebrow">{t("CURATOR ACTION", "ACCIÓN DEL CURADOR")}</span><h2>{t("Add official source", "Añadir fuente oficial")}</h2></div><Plus aria-hidden="true" /></header><div className="news-form-grid"><label>{t("Provider key", "Clave del proveedor")}<Input value={form.provider_key} placeholder="mistral" onChange={/** Update the normalized provider key. */ function update(event) { change("provider_key", event.target.value.toLowerCase().replace(/[^a-z0-9_-]/g, "")); }} /></label><label>{t("Provider name", "Nombre del proveedor")}<Input value={form.provider_name} placeholder="Mistral AI" onChange={/** Update the public provider name. */ function update(event) { change("provider_name", event.target.value); }} /></label><label>{t("Source name", "Nombre de la fuente")}<Input value={form.name} placeholder="Model release notes" onChange={/** Update the curator-facing source label. */ function update(event) { change("name", event.target.value); }} /></label><label className="wide">{t("Official HTTPS URL", "URL HTTPS oficial")}<Input value={form.url} onChange={/** Update the candidate official endpoint. */ function update(event) { change("url", event.target.value); }} /></label><label className="news-check"><input type="checkbox" checked={form.active} onChange={/** Choose whether a passing source becomes active immediately. */ function update(event) { change("active", event.target.checked); }} />{t("Activate after validation", "Activar después de validar")}</label></div>{testResult ? <div className={`notice ${testResult.passed ? "" : "error"}`}><FlaskConical aria-hidden="true" size={15} />{testResult.passed ? t("Safe fetch and extraction passed.", "La descarga y extracción seguras fueron aprobadas.") : String(testResult.code ?? t("Validation failed", "La validación falló"))}</div> : null}<div className="news-actions"><Button variant="outline" onClick={/** Run a side-effect-free live source test. */ function runTest() { void test(); }}><FlaskConical aria-hidden="true" />{t("Test source", "Probar fuente")}</Button><Button disabled={!form.provider_key || !form.provider_name || !form.name || !form.url.startsWith("https://")} onClick={/** Save the tested source through the protected registry endpoint. */ function save() { void create(); }}><Plus aria-hidden="true" />{t("Add source", "Añadir fuente")}</Button></div></section>
    <section className="news-panel news-suggestions"><header><div><span className="eyebrow">{t("REVIEW QUEUE", "COLA DE REVISIÓN")}</span><h2>{t("Discovered suggestions", "Sugerencias descubiertas")}</h2></div><span>{suggestions.filter(/** Count suggestions that still await a decision. */ function pending(value) { return value.status === "pending"; }).length}</span></header>{suggestions.filter(/** Show only undecided web discoveries. */ function pending(value) { return value.status === "pending"; }).map(/** Render an untrusted suggestion with explicit dismissal. */ function renderSuggestion(suggestion) { return <article key={suggestion.id}><div><strong>{suggestion.provider_name}</strong><a href={suggestion.url} target="_blank" rel="noopener noreferrer">{suggestion.url}</a><small>{t("Discovery only — never evidence until approved", "Solo descubrimiento; nunca es evidencia hasta su aprobación")}</small></div><Button variant="ghost" size="icon" aria-label={t("Dismiss suggestion", "Descartar sugerencia")} onClick={/** Record a curator dismissal for this suggestion. */ function reject() { void dismiss(suggestion); }}><X aria-hidden="true" /></Button></article>; })}{!suggestions.some(/** Detect whether the review queue contains a pending record. */ function pending(value) { return value.status === "pending"; }) ? <p className="news-empty"><Check aria-hidden="true" />{t("No suggestions await review.", "No hay sugerencias pendientes de revisión.")}</p> : null}</section>
  </div>;
}
